version: '3'
services:
  fpm:
    container_name: fpm
    restart: always
    image: dzamyatin/php73-1.0.10
    volumes:
      - ./app:/var/www/html #TODO rebuild container with code
      - ./xdebug.ini:/etc/php.d/xdebug.ini #TODO delete debug
  migration:
    image: dzamyatin/php73-1.0.10
    volumes:
      - ./app:/var/www/html #TODO rebuild container with code
    entrypoint: ["/var/www/html/bin/console", "doctrine:migrations:migrate", "--no-interaction"]
  nginx:
    container_name: nginx
    image: dzamyatin/nginx:1.0.1
    restart: always
    volumes:
      - ./app:/var/www/html #TODO rebuild container with code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9123:80
  redis:
    container_name: redis
    image: "redis:alpine"
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: root
    volumes:
      - ./data/db:/var/lib/mysql